/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.psicotest;

import javax.swing.JFrame;
import proyecto.psicotest.Ventanas.Goodenough;
import proyecto.psicotest.Ventanas.Machover;

/**
 *
 * @author D4ZC & Yooma
 */
public class MainMenu extends javax.swing.JFrame {

   
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null); /**Centrar la pantalla de inicio*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGoodenough = new javax.swing.JButton();
        btnMachover = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGoodenough.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGoodenough.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/testIicon.png"))); // NOI18N
        btnGoodenough.setText("Goodenough");
        btnGoodenough.setBorder(null);
        btnGoodenough.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGoodenough.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoodenoughActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoodenough, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 180, 50));

        btnMachover.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMachover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/testIicon.png"))); // NOI18N
        btnMachover.setText("Machover");
        btnMachover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnMachover, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 180, 50));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/salirIcon.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/output-onlinepngtools.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 310));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/img/ImagenHumana.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -40, 570, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0); /*Salir del programa*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGoodenoughActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoodenoughActionPerformed
        
            Goodenough x = new Goodenough (this);
            x.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnGoodenoughActionPerformed

    private void btnMachoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMachoverActionPerformed
        Machover y = new Machover (this);
        y.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMachoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoodenough;
    private javax.swing.JButton btnMachover;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}

